### ISSUE TITLE
Move refresh and sort options to toolbar

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#10]
Having `refresh` and `sort` options in toolbar, makes them easier and faster to access.

Those are the most used options, I think, and reducing taps (even if it's just one) is a UX improvement.

I'm also sure that toolbar has enough space for them, since it only has the overflow menu.

Thanks in advance.

**Comment by kollerlukas** [comment]
The toolbar might have enough space for refresh and sort to be always shown, but since this toolbar is shown in the context of images, that usually have a lot going on (color, contrast) I am trying to keep the toolbar as clean as possible to counter weigh the images. I might decide and add an option in settings, but I am not sure yet.

**Comment by jahirfiquitiva** [comment]
@kollerlukas  So, you're using the same toolbar for all sections/activities in the app? Well, then try hiding/removing those icons from toolbar when the toolbar is in other section that is not the albums view. Just a suggestion. If you decide to make it available in settings, that would be great too. Thanks.
