### ISSUE TITLE
Use right primary dark colors

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#12]
Right now, the app uses the same color for toolbar and status bar, and that makes it look a bit iOS-ish and that annoys me a bit.

Can you please use the right primary dark colors for both themes?
Light: `#e0e0e0`

Btw, for dark theme, can you please fix both primary and primary dark colors?
Primary Dark: `#000000`
Primary: `#212121`

PS: If you're using a transparent status bar, please add a black 20% opacity overlay, or `#33000000`. Height: Android 6+: `24dp` Android 5 and below: `25dp`.

Thanks in advance :)

**Comment by kollerlukas** [comment]
![screenshot_20170507-004008](https://cloud.githubusercontent.com/assets/16599370/25778818/1f78c19a-32be-11e7-9019-00430f9e5e2d.png)

I am added a ViewOverlay to the toolbar for the light theme.
I dont like the look of the semitransparent toolbar with a darker statusBar in the dark theme, thats why I am  leaving the toolbar in the dark as it is.

Btw you shouldn't use fixed values for the statusBar inset, because you are not guaranteed to have a statusBar (e.g. split screen), an OnApplyWindowInsetsListener is a better option to get the top inset for the statusBar. (only work on Lollipop and up).

**Comment by kollerlukas** [comment]
I am sorry, but I changed my mind on this one.
I think without the darker statusBar it looks nicer and cleaner.

**Comment by jahirfiquitiva** [comment]
@kollerlukas 
Oh, yeah, sorry, didn't thought about how it would look in split-screen.
Btw, can you please keep the darker status bar, even as an option in settings? I really love how it looks. Please.
Thanks in advance.
