### ISSUE TITLE
Rotate image by orientation sensor 

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#30]
![screenshot_20170605-131254](https://cloud.githubusercontent.com/assets/23030460/26775105/0ca80608-49f1-11e7-99e5-cce0ce7dcdde.png)

**Comment by kollerlukas** [comment]
What would be the difference to the default orientation change.

**Comment by jerryn70** [comment]
If we enabled orientation by sensor then the image will automatically rotate to landscape or to portrait according to sensor, even if the phones auto rotate option is off.

**Comment by jerryn70** [comment]
For more reference you can check this Gallery : https://github.com/SimpleMobileTools/Simple-Gallery

**Comment by kollerlukas** [comment]
I am sorry, but I don't think is a feature a gallery app should handle.
In my opinion this should be handled by the Android system.
If this is not working for you, you can try to use apps like Tasker to make this feature happen.
As for now I will not implement this feature.

**Comment by pedroemonteiro** [comment]
Come on man, this is one of the most handy features to have. I always have my phone set to rotation lock on portrait, but want only the image view to rotate, this is possibly on other gallery apps. Please reconsider.

**Comment by alekksander** [comment]
i agree with @pedroemonteiro  this is a _very_ useful feature. some other picture viewers have this, and it's one remaining thing that stops me from using CR as my main viewer app. @kollerlukas  Please reconsider. 

ps. do You imagine for instance that horizontal games displays in portrait mode because it's locked by android? some photos are made for horizontal, others for vertical viewing, while whole android itself is fine in vertical only.
