### ISSUE TITLE
Maximum brightness when viewing images

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#31]
It will be great if there is an option

**Comment by kollerlukas** [comment]
Why do you need the maximum brightness when looking at pictures?

**Comment by jerryn70** [comment]
Normally i use low brightness settings for better batter . Viewing images in low brightness is not that much detail . That's why this

**Comment by kollerlukas** [comment]
I don't feel like this is a nessecary feature, since you are easily able to just adjust the brightness yourself.
I might consider adding this feature in the future.

**Comment by ValeraVi** [comment]
+1 for this option. "QickPic" and "Piktures" app had this options - using this always. Very useful to see more details of photo / video. Or when you show photo/video to several persons. Manual brightness increase is not useful as you need to do a lot of taps... :)

**Comment by evilphish** [comment]
I would also like to vote for this feature @kollerlukas , let me explain why. I use the auto brightness mode with android to conserve battery and usually set the "average brightness" slider a bit on the low side for this very reason. The resulting brightness range is enough to read text messages or look at other things that feature a good contrast. However, if I want to look at a picture the finer details often get lost as the lower brightness kills the contrast. Manually setting and resetting the brightness each time is quite annoying. Sitting outside at lunch with a friend, just want to show him a picture real quick and I first have to set the brightness to maximum, and afterwards return it to the position it was before. As Valera mentioned, this feature was actually available with the QuickPic gallery before the developer sold the app to Cheetah Mobile and it went downhill from there. I always had this feature enabled, especially if you are outside in direct sunlight in helps a lot. Basically when looking at pictures, maximum brightness is the way to go as the result most closely resembles what you would see on a pc monitor. 

To me, this feature is about the most important thing missing from your otherwise excellent app. It just saves so much time. Could be a simple On/Off switch as it was with QuickPic in the settings. As in "Use maximum brightness when viewing pictures? Y/N"

So, pretty please with sugar on top, this would be very very very much appreciated. ;)
