### ISSUE TITLE
Writing on a removable Storage device (SD card, USB stick)

### ISSUE THREAD

**Issue by kollerlukas** [kollerlukas/Camera-Roll-Android-App#39]
App need to request permission to be able to write (delete, move and/or copy) to a removable Storage device.

**Comment by jerryn70** [comment]
In change log version 1.5.2 claims that it can delete/move/copy files in sd card. 

When I tested creating files or folders is not working.
Moving is not working.

And the annoying thing is everytime it ask to grant permission to copy / delete files in sd card.

**Comment by kollerlukas** [comment]
Moving does not work, beacuse I couldn't find a way to properly move files from storage to removable  storage or vice versa.

Yeah, the permission is annoying. But for now I don't know how to handle multiple removable storage devices (usb stick, sd card, ...).  I will try my best to fix this as soon as possible.

**Comment by kollerlukas** [comment]
The annoying permission should be gone now
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/94b07b2081607b67a00a41c8041e497d50f775f7

**Comment by pink-bird** [comment]
Just downloaded **version 1.5.2 beta** from Play Store. 
Still having the issue, to grant access for external microSD card every time I start the app (Android 7.0). Same happens when already granted access and then want to delete pictures.   

![screenshot_20170709-115256](https://user-images.githubusercontent.com/19912504/27992992-d38b7768-64a0-11e7-8aa4-3737e6a14826.png)

**Comment by kollerlukas** [comment]
I fixed this issue, but didn't update the app on the Play Store yet.
The next update will fix this issue.
