### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by ikocevski** [kollerlukas/Camera-Roll-Android-App#51]
I'm standing here thinking, it's probably the most beautiful gallery I've ever seen and it's a shame I can't update it regularly since I don't use Play Store (or anything Google for that matter). So, would you please consider publishing it on F-Droid, too?

**Comment by ikocevski** [comment]
@kollerlukas Nope?

**Comment by kollerlukas** [comment]
Hi! Sorry for not answering.
I would love to submit my app on FDroid, but at the moment I don't know how to do it and I don't have the time to do it.
I will do it as soon as possible, but that might be in a few weeks. 
Sorry!

**Comment by ikocevski** [comment]
Yay! Glad to hear that.. take your time, no probs ;)

**Comment by dkanada** [comment]
I think I was able to get this working for F-Droid with a few minor changes, although it seemed almost too easy so maybe I went wrong somewhere.

The main change is adding the following to build.gradle so your dependencies are pulled from a repository on F-Droid's whitelist. They only allows open source dependencies, so Google Play Services and any closed source analytics can't be added in the future if you wanted to add those at some point.

<code>
repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}
</code>

I had three issues building the app as well, not sure if any of these will also be issues with F-Droid but I wasn't able to get it working without the following changes.

- renaming albumItem_not_selected.xml, albumItem_selected.xml, and albumItem_selected_indicator so that they only used lowercase characters
- removing roboto_mono_regular.ttf from the app entirely, I have no clue why android studio wasn't picking it up but I couldn't compile due to errors from not finding the file
- downgrading gradle to version 2.3.2 since it couldn't find the alpha version

**Comment by 464247853** [comment]
thank you :)

**Comment by 464247853** [comment]
Looking forward to it :)

**Comment by relan** [comment]
F-Droid maintainer here. I'd love to see Camera Roll on F-Droid too. There's a minor problem that prevents the inclusion though: pre-release version of Gradle plugin and, consequently, Gradle itself. Once you move to a stable version, let me know, I'll do the rest.

**Comment by kollerlukas** [comment]
Unfortunately I am already using the new xml-Fonts and I am already supplying an adaptive icon.
In order to downgrade I would have to remove those.

**Comment by relan** [comment]
I meant after you _upgrade_ to a new stable version of Android Gradle plugin and Gradle, I'll happily add Camera Roll to F-Droid. No need to downgrade.

**Comment by IzzySoft** [comment]
Until it turns up in the official repo: It's already [in mine](https://apt.izzysoft.de/fdroid/index/apk/us.koller.cameraroll) for a while :wink:

**Comment by dkanada** [comment]
@IzzySoft slightly unrelated question but do you mention anywhere which apps are not sourced directly from their respective repositories? I read somewhere on your site that in most cases you use only officially built apk files but that there were some exceptions.

**Comment by IzzySoft** [comment]
@dkanada no need to, as the answer is simple: None. As you correctly remember, the repo's "[info page](http://apt.izzysoft.de/fdroid/index/info)" states those details: I don't build any `.apk` myself. All of them are provided by their resp. developers – usually on the `releases/` pages of their repos, sometimes directly within the repo, and very rarely via another dedicated page/link. Otherwise, they couldn't be signed with the resp. developer's key :wink:

**Comment by relan** [comment]
Now F-Droid has everything to build v1.6.2 Beta. @kollerlukas, should I push it?

**Comment by kollerlukas** [comment]
@relan Really? I am still using a beta release of gradle... . But, if you can sure.

**Comment by relan** [comment]
> I am still using a beta release of gradle

Yeah, I was too fast. While we have Gradle 4.1, Android Gradle plugin is still 3.0.0-beta3. Google haven't published the source code of it, so it's proprietary software for now. Let's wait.

**Comment by gabrielelucci** [comment]
Eagerly waiting for this to be included in F-Droid main repository. Hands down best gallery app I ever seen. Thank you @kollerlukas, also for distributing it with a free software license.

**Comment by kollerlukas** [comment]
@relan Just updated the gradle plugin to the stable version 3.0.0!

**Comment by relan** [comment]
[Added](https://gitlab.com/fdroid/fdroiddata/commit/4fcef47d2f837c356f6fb0aafb86edce1e3050f3). Should be available on F-Droid in a few days.

**Comment by kollerlukas** [comment]
@relan Thanks!

**Comment by IzzySoft** [comment]
For those about to switch repos (from mine to the official): remember the signature change (F-Droid signs with its own key). So unless using something like XInstaller (Xposed module to tweak the package installer) you'll have to uninstall first.

I'll keep Camera Roll in my repo though (unless @kollerlukas objects), where updates usually arrive a few days earlier¹ – so choice is yours.

----

<sup>¹ due to the strange tag format (`<versionCode>-v<versionName>` instead of either `versionCode` or `v<versionName>` I have to catch them manually, though, so there might be delays</sup>

**Comment by ikocevski** [comment]
This app is amazing, even more so now that it's available on F-Droid. Thank you @relan for making this possible and most importantly thank you @kollerlukas for developing such a great app. Cheers!

**Comment by alexanderadam** [comment]
Hu, it isn't yet in the [official repositories](https://f-droid.org/packages/#q=camera%20roll) yet, right?

**Comment by relan** [comment]
It's live: https://f-droid.org/en/packages/us.koller.cameraroll/

**Comment by kollerlukas** [comment]
@relan Thanks!!
