### ISSUE TITLE
Theme primary color

### ISSUE THREAD

**Issue by lologolo** [kollerlukas/Camera-Roll-Android-App#73]
Can you add a simple color picker to change primary color?
This could be a good library : https://github.com/DASAR/ShiftColorPicker

Beautiful app  😃

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kollerlukas** [comment]
I am sorry but for now I am not going to add customizable colors, since the way I implemented the themes it would take quite so work to get that working.
Furthermore I think in apps with a lot of images the color should come from the images. And the UI shouldn't distract from the images with flashy colors.
Sorry.
