### ISSUE TITLE
Edit Exif improvements

### ISSUE THREAD

**Issue by IzzySoft** [kollerlukas/Camera-Roll-Android-App#89]
When editing Exif data, it would be great if we could add a comment (Exif supports this). Especially useful when traveling (notes for further processing, specific details, etc). If that's already there and I just missed it, a pointer is always welcome :wink:

While on it: "Orientation" would be nice to have as "drop-down" with some description (e.g. Rotate 90, Rotate 180, Rotate 270 – with a remark of the direction, e.g. "CW" (clock-wise) to avoid confusion). The "average mortal" is unlikely to remember the "bare numbers" and what they stand for. Could also be "optional" (in case some "pro" insists on editing it raw) or have an entry like "raw" which then permits "raw editing" of those "numbers".

**Comment by kollerlukas** [comment]
![screenshot_20170914-150344](https://user-images.githubusercontent.com/16599370/30431193-17b521cc-995e-11e7-9b2e-79d85d6e9816.png)

Just added Spinners for Orintation and Whitebalance.

I also noticed that since I am using the support Library ExifInterface I was unnessesarily restricting devices below api level 24 (Nougat) to a smaller set of ExifTags. Also changed that.

**Comment by IzzySoft** [comment]
Cool, thanks! Does that also add the comment field (as a side-effect of that API-24 fix)? My current devices are all pre-Nougat, so that indeed could have been the reason. If so, out of curiosity: About when to expect the next release having the fix included? Going on vacation soon, which my first paragraph was about :wink:

**Comment by kollerlukas** [comment]
I going to push the update later today.
